### ISSUE TITLE
Missing the time.windows.com url

### ISSUE THREAD

**Issue by BurgerhoutJ** [mmelkersen/EndpointManager#1]
Hi Mattias,

I'm missing the NTP url, time.windows.com.
It's also one of the requirements for autopilot.
https://docs.microsoft.com/en-us/mem/autopilot/networking-requirements#network-time-protocol-ntp-sync

**Comment by mmelkersen** [comment]
Hi @BurgerhoutJ it is fixed now. Thanks for the feedback!

**Comment by BurgerhoutJ** [comment]
Thanks @mmelkersen !
