### ISSUE TITLE
Fails to start on a fresh Win 10 Hyper-V VM

### ISSUE THREAD

**Issue by igor-teresco** [mmelkersen/EndpointManager#2]
MSI installs ok, but when trying to execute - displays briefly black screen and nothing happens.

Executing Rerun script in admin powershell shows the error - 
Module 'Microsoft.Graph.Intune' is required. To install it call: Install-Module 'Microsoft.Graph.Intune' -Scope CurrentUser
In C:\ProgramData\IntuneDebugTools\RerunWin32.ps1:68 Zeichen:13

After manually installing this module execution continues.

**Comment by mmelkersen** [comment]
Thanks Igor, I will solve that, so it automatically install the module.

**Comment by mmelkersen** [comment]
It has been resolved in the newer version 1.3 and later
